//src/api/categoriesApi.js
const categoriesData = {
    mainNavigation: [
        {
            id: 'home',
            name: 'Home',
            slug: 'home',
            path: '/',
            icon: 'Home.svg',
        },
        {
            id: 'recently',
            name: 'Recently player',
            slug: 'recent',
            path: '/recent',
            icon: 'Recent.svg',
        },
        {
            id: 'new',
            name: 'New',
            slug: 'new',
            path: '/new',
            icon: 'New.svg',
        },
        {
            id: 'trending',
            name: 'Trending now',
            slug: 'trending',
            path: '/trending',
            icon: 'Trending.svg',
        },
        {
            id: 'updated',
            name: 'Updated',
            slug: 'updated',
            path: '/updated',
            icon: 'Updated.svg',
        },
        {
            id: 'originals',
            name: 'Originals',
            slug: 'originals',
            path: '/originals',
            icon: 'Originals.svg',
        },
        {
            id: 'multiplayer',
            name: 'Multiplayer',
            slug: 'multiplayer',
            path: '/multiplayer',
            icon: 'Multiplayer.svg',
        },
    ],
    categoriesGame: [
        {
            id: '2-player',
            name: '2 Player',
            slug: '2-player',
            path: '/2player',
            icon: '2players.svg',
        },
        {
            id: 'action',
            name: 'Action',
            slug: 'action',
            path: '/action',
            icon: 'Action.svg',
        },
        {
            id: 'adventure',
            name: 'Adventure',
            slug: 'adventure',
            path: '/adventure',
            icon: 'Adventure.svg',
        },

        {
            id: 'basketball',
            name: 'Basketball',
            slug: 'basketball',
            path: '/basketball',
            icon: 'Basketball.svg',
        },
        {
            id: 'beauty',
            name: 'Beauty',
            slug: 'beauty',
            path: '/beauty',
            icon: 'Beauty.svg',
        },
        {
            id: 'bike',
            name: 'Bike',
            slug: 'bike',
            path: '/bike',
            icon: 'Bike.svg',
        },
        {
            id: 'car',
            name: 'Car',
            slug: 'car',
            path: '/car',
            icon: 'Car.svg',
        },
        {
            id: 'card',
            name: 'Card',
            slug: 'card',
            path: '/card',
            icon: 'Card.svg',
        },
        {
            id: 'casual',
            name: 'Casual',
            slug: 'casual',
            path: '/casual',
            icon: 'Casual.svg',
        },

        {
            id: 'clicker',
            name: 'Clicker',
            slug: 'clicker',
            path: '/Clicker',
            icon: 'Clicker.svg',
        },

        {
            id: 'controller',
            name: 'Controller',
            slug: 'controller',
            path: '/controller',
            icon: 'Controller.svg',
        },
        {
            id: 'dress-up',
            name: 'Dress Up',
            slug: 'dress-up',
            path: '/dress-up',
            icon: 'DressUp.svg',
        },
        {
            id: 'driving',
            name: 'Driving',
            slug: 'driving',
            path: '/driving',
            icon: 'Driving.svg',
        },
        {
            id: 'escape',
            name: 'Escape',
            slug: 'escape',
            path: '/escape',
            icon: 'Escape.svg',
        },
        {
            id: 'flash',
            name: 'Flash',
            slug: 'flash',
            path: '/flash',
            icon: 'Flash.svg',
        },
        {
            id: 'fps',
            name: 'FPS',
            slug: 'fps',
            path: '/fps',
            icon: 'FPS.svg',
        },
        {
            id: 'horror',
            name: 'Horror',
            slug: 'horror',
            path: '/horror',
            icon: 'Horror.svg',
        },
        {
            id: 'io-games',
            name: '.io Games',
            slug: 'io-games',
            path: '/io-games',
            icon: 'io.svg',
        },
        {
            id: 'mahjong',
            name: 'Mahjong',
            slug: 'mahjong',
            path: '/mahjong',
            icon: 'Mahjong.svg',
        },
        {
            id: 'minecraft',
            name: 'Minecraft',
            slug: 'minecraft',
            path: '/minecraft',
            icon: 'Minecraft.svg',
        },
        {
            id: 'pool',
            name: 'Pool',
            slug: 'pool',
            path: '/pool',
            icon: 'Pool.svg',
        },
        {
            id: 'puzzle',
            name: 'Puzzle',
            slug: 'puzzle',
            path: '/puzzle',
            icon: 'Puzzle.svg',
        },
        {
            id: 'shooting',
            name: 'Shooting',
            slug: 'shooting',
            path: '/shooting',
            icon: 'Shooting.svg',
        },
        {
            id: 'soccer',
            name: 'Soccer',
            slug: 'soccer',
            path: '/soccer',
            icon: 'Soccer.svg',
        },

        {
            id: 'sports',
            name: 'Sports',
            slug: 'sports',
            path: '/sports',
            icon: 'Sports.svg',
        },
        {
            id: 'stickman',
            name: 'Stickman',
            slug: 'stickman',
            path: '/stickman',
            icon: 'Stickman.svg',
        },
        {
            id: 'tower-defense',
            name: 'Tower Defense',
            slug: 'tower-defense',
            path: '/tower-defense',
            icon: 'TowerDefense.svg',
        },
    ],
    footerNav: [
        {
            id: 'tags',
            name: 'Tags',
            slug: 'tags',
            path: '/tags',
            icon: 'Tags.svg',
        },
    ],
};
export { categoriesData };
