export const gameApi = [
    {
        id: 1,
        title: 'Ragdoll Archers',
        slug: 'ragdoll-archers',
        thumbnail: 'ragdoll-archers.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            '2-player',
            'action',
            'adventure',
            'basketball',
            'beauty',
            'bike',
            'card',
            'casual',
            'controller',
            'dress-up',
            'fps',
            'horror',
            'puzzle',
        ],
        releaseDate: '2025-05-15',
        lastUpdated: '2025-05-20',
        playCount: 15000,
        isMultiplayer: true,
    },
    {
        id: 2,
        title: 'Screw Out Bolts And Nuts',
        slug: 'screw-out-bolts-and-nuts',
        thumbnail: 'screw-out-bolts-and-nuts.jpg',
        url: 'https://cloud.onlinegames.io/games/2021/1/apocalypse-truck/index-og.html',
        categories: [
            'action',
            'adventure',
            'bike',
            'car',
            'clicker',
            'controller',
            'driving',
            'escape',
            'mahjong',
            'minecraft',
            'puzzle',
            'sports',
            'tower-defense',
        ],
        releaseDate: '2025-04-10',
        lastUpdated: '2025-05-01',
        playCount: 8000,
        isMultiplayer: false,
    },
    {
        id: 3,
        title: 'ShellShockers.io',
        slug: 'shell-shockers-io',
        thumbnail: 'shell-shockers-io.jpg',
        url: 'https://www.onlinegames.io/games/2021/unity/stack-fire-ball/index.html',
        categories: [
            '2-player',
            'fps',
            'horror',
            'io-games',
            'pool',
            'puzzle',
            'shooting',
            'soccer',
            'sports',
            'stickman',
            'tower-defense',
        ],
        releaseDate: '2025-03-01',
        lastUpdated: '2025-05-25',
        playCount: 25000,
        isMultiplayer: true,
    },
    {
        id: 4,
        title: 'Skill Warz',
        slug: 'skill-warz',
        thumbnail: 'skill-warz.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            'action',
            'basketball',
            'beauty',
            'card',
            'casual',
            'controller',
            'driving',
            'flash',
            'minecraft',
            'puzzle',
            'shooting',
            'stickman',
        ],
        releaseDate: '2025-05-10',
        lastUpdated: '2025-05-15',
        playCount: 12000,
        isMultiplayer: false,
    },
    {
        id: 5,
        title: 'Tower Swap',
        slug: 'tower-swap',
        thumbnail: 'tower-swap.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            'adventure',
            'bike',
            'car',
            'clicker',
            'dress-up',
            'escape',
            'mahjong',
            'pool',
            'puzzle',
            'soccer',
            'sports',
            'tower-defense',
        ],
        releaseDate: '2025-04-20',
        lastUpdated: '2025-04-25',
        playCount: 6000,
        isMultiplayer: false,
    },
    {
        id: 6,
        title: 'Tropical Merge',
        slug: 'tropical-merge',
        thumbnail: 'tropical-merge.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            '2-player',
            'beauty',
            'card',
            'casual',
            'controller',
            'driving',
            'fps',
            'horror',
            'io-games',
            'puzzle',
            'shooting',
            'stickman',
        ],
        releaseDate: '2025-05-05',
        lastUpdated: '2025-05-10',
        playCount: 18000,
        isMultiplayer: true,
    },
    {
        id: 7,
        title: 'Slice Master',
        slug: 'slice-master',
        thumbnail: 'slice-master.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            'action',
            'basketball',
            'bike',
            'car',
            'clicker',
            'escape',
            'flash',
            'mahjong',
            'minecraft',
            'pool',
            'puzzle',
            'sports',
        ],
        releaseDate: '2025-04-15',
        lastUpdated: '2025-05-01',
        playCount: 9000,
        isMultiplayer: false,
    },
    {
        id: 8,
        title: 'Wordmeister',
        slug: 'wordmeister',
        thumbnail: 'wordmeister.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            'adventure',
            'beauty',
            'card',
            'casual',
            'controller',
            'dress-up',
            'fps',
            'horror',
            'io-games',
            'puzzle',
            'soccer',
            'tower-defense',
        ],
        releaseDate: '2025-03-15',
        lastUpdated: '2025-04-01',
        playCount: 7000,
        isMultiplayer: false,
    },
    {
        id: 9,
        title: 'Words Of Wonders',
        slug: 'words-of-wonders',
        thumbnail: 'words-of-wonders.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            '2-player',
            'action',
            'bike',
            'car',
            'clicker',
            'driving',
            'escape',
            'mahjong',
            'minecraft',
            'pool',
            'puzzle',
            'shooting',
        ],
        releaseDate: '2025-05-01',
        lastUpdated: '2025-05-05',
        playCount: 11000,
        isMultiplayer: true,
    },
    {
        id: 10,
        title: 'Stone Crass',
        slug: 'stone-crass',
        thumbnail: 'stone-crass.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            'basketball',
            'beauty',
            'card',
            'casual',
            'controller',
            'flash',
            'horror',
            'io-games',
            'puzzle',
            'soccer',
            'sports',
            'stickman',
        ],
        releaseDate: '2025-04-01',
        lastUpdated: '2025-04-10',
        playCount: 5000,
        isMultiplayer: false,
    },
    {
        id: 11,
        title: 'Hazmob Fps Online Shooter',
        slug: 'hazmob-fps-online-shooter',
        thumbnail: 'hazmob-fps-online-shooter.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            '2-player',
            'action',
            'fps',
            'io-games',
            'mahjong',
            'minecraft',
            'pool',
            'puzzle',
            'shooting',
            'sports',
            'tower-defense',
        ],
        releaseDate: '2025-05-20',
        lastUpdated: '2025-05-25',
        playCount: 20000,
        isMultiplayer: true,
    },
    {
        id: 12,
        title: 'Hidden Objects',
        slug: 'hidden-objects',
        thumbnail: 'hidden-objects.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            'adventure',
            'bike',
            'car',
            'clicker',
            'controller',
            'dress-up',
            'escape',
            'flash',
            'horror',
            'puzzle',
            'soccer',
            'stickman',
        ],
        releaseDate: '2025-04-05',
        lastUpdated: '2025-04-15',
        playCount: 6500,
        isMultiplayer: false,
    },
    {
        id: 13,
        title: 'Mahjongg Solitaire',
        slug: 'mahjongg-solitaire',
        thumbnail: 'mahjongg-solitaire.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            '2-player',
            'beauty',
            'card',
            'casual',
            'driving',
            'fps',
            'mahjong',
            'minecraft',
            'pool',
            'puzzle',
            'shooting',
            'sports',
        ],
        releaseDate: '2025-03-20',
        lastUpdated: '2025-04-10',
        playCount: 8500,
        isMultiplayer: true,
    },
    {
        id: 14,
        title: 'Mahjong Connect',
        slug: 'mahjong-connect',
        thumbnail: 'mahjong-connect.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            'action',
            'basketball',
            'bike',
            'controller',
            'dress-up',
            'escape',
            'flash',
            'horror',
            'io-games',
            'puzzle',
            'soccer',
            'tower-defense',
        ],
        releaseDate: '2025-04-25',
        lastUpdated: '2025-05-01',
        playCount: 9500,
        isMultiplayer: false,
    },
    {
        id: 15,
        title: 'Piles Of Mahjong',
        slug: 'piles-of-mahjong',
        thumbnail: 'piles-of-mahjong.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            '2-player',
            'adventure',
            'car',
            'casual',
            'clicker',
            'driving',
            'fps',
            'mahjong',
            'minecraft',
            'pool',
            'puzzle',
            'shooting',
        ],
        releaseDate: '2025-05-05',
        lastUpdated: '2025-05-10',
        playCount: 11000,
        isMultiplayer: true,
    },
    {
        id: 16,
        title: 'Italian Brainrot Clicker',
        slug: 'italian-brainrot-clicker',
        thumbnail: 'italian-brainrot-clicker.jpg',
        isBigs: true,
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            'basketball',
            'beauty',
            'bike',
            'card',
            'controller',
            'dress-up',
            'escape',
            'horror',
            'io-games',
            'puzzle',
            'sports',
            'stickman',
        ],
        releaseDate: '2025-05-15',
        lastUpdated: '2025-05-20',
        playCount: 13000,
        isMultiplayer: false,
    },
    {
        id: 17,
        title: 'Nuts Puzzle Sort By Color',
        slug: 'nuts-puzzle-sort-by-color',
        thumbnail: 'nuts-puzzle-sort-by-color.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            '2-player',
            'action',
            'car',
            'casual',
            'clicker',
            'driving',
            'flash',
            'mahjong',
            'minecraft',
            'pool',
            'puzzle',
            'soccer',
        ],
        releaseDate: '2025-04-10',
        lastUpdated: '2025-04-20',
        playCount: 7000,
        isMultiplayer: true,
    },
    {
        id: 18,
        title: 'Poly Track',
        slug: 'poly-track',
        thumbnail: 'poly-track.jpg',
        isBigs: true,
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            'adventure',
            'basketball',
            'card',
            'controller',
            'fps',
            'horror',
            'io-games',
            'puzzle',
            'shooting',
            'sports',
            'stickman',
            'tower-defense',
        ],
        releaseDate: '2025-05-25',
        lastUpdated: '2025-05-28',
        playCount: 22000,
        isMultiplayer: false,
    },
    {
        id: 19,
        title: 'Fairyland Merge And Magic',
        slug: 'fairyland-merge-and-magic',
        thumbnail: 'fairyland-merge-and-magic.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            '2-player',
            'beauty',
            'bike',
            'casual',
            'clicker',
            'driving',
            'escape',
            'mahjong',
            'pool',
            'puzzle',
            'soccer',
            'sports',
        ],
        releaseDate: '2025-04-15',
        lastUpdated: '2025-04-25',
        playCount: 10000,
        isMultiplayer: true,
    },
    {
        id: 20,
        title: 'Farm Merge Valley',
        slug: 'farm-merge-valley',
        thumbnail: 'farm-merge-valley.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            'action',
            'adventure',
            'card',
            'controller',
            'dress-up',
            'flash',
            'horror',
            'io-games',
            'minecraft',
            'puzzle',
            'shooting',
            'stickman',
        ],
        releaseDate: '2025-03-10',
        lastUpdated: '2025-04-01',
        playCount: 8000,
        isMultiplayer: false,
    },
    {
        id: 21,
        title: '8 Ball Billiards Classic',
        slug: '8-ball-billiards-classic',
        thumbnail: '8-ball-billiards-classic.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            '2-player',
            'basketball',
            'beauty',
            'car',
            'casual',
            'clicker',
            'fps',
            'mahjong',
            'pool',
            'puzzle',
            'soccer',
            'sports',
        ],
        releaseDate: '2025-05-01',
        lastUpdated: '2025-05-05',
        playCount: 14000,
        isMultiplayer: true,
    },
    {
        id: 22,
        title: 'Blockbuster Puzzle',
        slug: 'blockbuster-puzzle',
        thumbnail: 'blockbuster-puzzle.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            'action',
            'bike',
            'card',
            'controller',
            'driving',
            'escape',
            'flash',
            'horror',
            'io-games',
            'puzzle',
            'shooting',
            'tower-defense',
        ],
        releaseDate: '2025-04-20',
        lastUpdated: '2025-04-25',
        playCount: 6000,
        isMultiplayer: false,
    },
    {
        id: 23,
        title: 'Count Masters Stickman',
        slug: 'count-masters-stickman',
        thumbnail: 'count-masters-stickman.jpg',
        isBigs: true,
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            '2-player',
            'adventure',
            'beauty',
            'casual',
            'clicker',
            'fps',
            'mahjong',
            'minecraft',
            'pool',
            'puzzle',
            'soccer',
            'stickman',
        ],
        releaseDate: '2025-05-10',
        lastUpdated: '2025-05-15',
        playCount: 16000,
        isMultiplayer: true,
    },
    {
        id: 24,
        title: 'Country Life Meadows',
        slug: 'country-life-meadows',
        thumbnail: 'country-life-meadows.jpg',
        isBigs: true,
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            'basketball',
            'car',
            'card',
            'controller',
            'driving',
            'escape',
            'flash',
            'horror',
            'io-games',
            'puzzle',
            'shooting',
            'sports',
        ],
        releaseDate: '2025-04-05',
        lastUpdated: '2025-04-15',
        playCount: 9000,
        isMultiplayer: false,
    },
    {
        id: 25,
        title: 'Airport Security',
        slug: 'airport-security',
        thumbnail: 'airport-security.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            '2-player',
            'action',
            'beauty',
            'bike',
            'casual',
            'clicker',
            'fps',
            'minecraft',
            'pool',
            'puzzle',
            'soccer',
            'tower-defense',
        ],
        releaseDate: '2025-05-20',
        lastUpdated: '2025-05-25',
        playCount: 17000,
        isMultiplayer: true,
    },
    {
        id: 26,
        title: 'Bloxd.io',
        slug: 'bloxd-io',
        thumbnail: 'bloxd-io.jpg',
        isBigs: true,
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            'adventure',
            'basketball',
            'card',
            'controller',
            'driving',
            'escape',
            'flash',
            'horror',
            'mahjong',
            'puzzle',
            'shooting',
            'stickman',
        ],
        releaseDate: '2025-05-15',
        lastUpdated: '2025-05-20',
        playCount: 30000,
        isMultiplayer: true,
    },
    {
        id: 27,
        title: 'Designville Merge Design',
        slug: 'designville-merge-design',
        thumbnail: 'designville-merge-design.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            '2-player',
            'action',
            'beauty',
            'bike',
            'casual',
            'clicker',
            'fps',
            'io-games',
            'minecraft',
            'pool',
            'puzzle',
            'sports',
        ],
        releaseDate: '2025-04-10',
        lastUpdated: '2025-04-20',
        playCount: 7500,
        isMultiplayer: true,
    },
    {
        id: 28,
        title: 'Crazy Office Slap And Smash',
        slug: 'crazy-office-slap-and-smash',
        thumbnail: 'crazy-office-slap-and-smash.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            'adventure',
            'car',
            'card',
            'controller',
            'driving',
            'escape',
            'flash',
            'horror',
            'io-games',
            'puzzle',
            'soccer',
            'tower-defense',
        ],
        releaseDate: '2025-03-25',
        lastUpdated: '2025-04-05',
        playCount: 8500,
        isMultiplayer: false,
    },
    {
        id: 29,
        title: 'Defender Idle 2',
        slug: 'defender-idle-2',
        thumbnail: 'defender-idle-2.jpg',
        isBigs: true,
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            '2-player',
            'action',
            'basketball',
            'beauty',
            'casual',
            'clicker',
            'fps',
            'io-games',
            'minecraft',
            'pool',
            'puzzle',
            'shooting',
        ],
        releaseDate: '2025-05-05',
        lastUpdated: '2025-05-10',
        playCount: 19000,
        isMultiplayer: true,
    },
    {
        id: 30,
        title: 'Crazy Flips 3D',
        slug: 'crazy-flips-3d',
        thumbnail: 'crazy-flips-3d.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: [
            'adventure',
            'bike',
            'car',
            'controller',
            'driving',
            'escape',
            'flash',
            'horror',
            'mahjong',
            'puzzle',
            'soccer',
            'sports',
            'stickman',
        ],
        releaseDate: '2025-04-15',
        lastUpdated: '2025-04-20',
        playCount: 9500,
        isMultiplayer: false,
    },
    {
        id: 31,
        title: 'Crazy Guys',
        slug: 'crazy_guys',
        originalThumbnail: 'crazy-guys.jpg',
        thumbnail: 'crazy-guys.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['action', 'adventure', 'casual', 'controller', 'stickman', 'shooting', 'io-games'],
        releaseDate: '2025-05-10',
        lastUpdated: '2025-05-15',
        playCount: 12000,
        isMultiplayer: true,
    },
    {
        id: 32,
        title: 'Space Waves',
        slug: 'space_waves',
        originalThumbnail: 'space-waves.jpg',
        thumbnail: 'space-waves.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['action', 'adventure', 'casual', 'controller', 'puzzle', 'shooting'],
        releaseDate: '2025-05-05',
        lastUpdated: '2025-05-10',
        playCount: 10000,
        isMultiplayer: false,
    },
    {
        id: 33,
        title: 'Sky Riders',
        slug: 'sky_riders',
        originalThumbnail: 'sky-riders.jpg',
        thumbnail: 'sky-riders.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['action', 'adventure', 'controller', 'driving', 'sports'],
        releaseDate: '2025-04-25',
        lastUpdated: '2025-05-01',
        playCount: 9000,
        isMultiplayer: false,
    },
    {
        id: 34,
        title: 'Evowars',
        slug: 'evowars',
        originalThumbnail: 'evowars.jpg',
        thumbnail: 'evowars.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['2-player', 'action', 'io-games', 'shooting', 'stickman'],
        releaseDate: '2025-05-15',
        lastUpdated: '2025-05-20',
        playCount: 15000,
        isMultiplayer: true,
    },
    {
        id: 35,
        title: 'Cubes 2048 Io',
        slug: 'cubes_2048_io',
        originalThumbnail: 'cubes-2048-io.jpg',
        thumbnail: 'cubes-2048-io.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['io-games', 'puzzle', 'casual', 'clicker'],
        releaseDate: '2025-05-01',
        lastUpdated: '2025-05-05',
        playCount: 13000,
        isMultiplayer: true,
    },
    {
        id: 36,
        title: 'Holey Io',
        slug: 'holey_io',
        originalThumbnail: 'holey-io.jpg',
        thumbnail: 'holey-io.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['io-games', 'action', 'casual', 'controller'],
        releaseDate: '2025-04-20',
        lastUpdated: '2025-04-25',
        playCount: 11000,
        isMultiplayer: true,
    },
    {
        id: 37,
        title: 'Escape From Prison Multiplayer',
        slug: 'escape_from_prison_multiplayer',
        originalThumbnail: 'escape-from-prison-multiplayer.jpg',
        thumbnail: 'escape-from-prison-multiplayer.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['2-player', 'action', 'adventure', 'escape', 'multiplayer'],
        releaseDate: '2025-05-20',
        lastUpdated: '2025-05-25',
        playCount: 14000,
        isMultiplayer: true,
    },
    {
        id: 38,
        title: 'Mini Golf Club',
        slug: 'mini_golf_club',
        originalThumbnail: 'mini-golf-club.jpg',
        thumbnail: 'mini-golf-club.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['sports', 'casual', '2-player', 'controller'],
        releaseDate: '2025-04-15',
        lastUpdated: '2025-04-20',
        playCount: 8000,
        isMultiplayer: true,
    },
    {
        id: 39,
        title: 'Gridpunk 3V3 Battle Royale',
        slug: 'gridpunk_3v3_battle_royale',
        originalThumbnail: 'gridpunk-3v3-battle-royale.jpg',
        thumbnail: 'gridpunk-3v3-battle-royale.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['2-player', 'action', 'shooting', 'io-games', 'fps'],
        releaseDate: '2025-05-25',
        lastUpdated: '2025-05-28',
        playCount: 20000,
        isMultiplayer: true,
    },
    {
        id: 40,
        title: 'Cgfc',
        slug: 'cgfc',
        originalThumbnail: 'cgfc.jpg',
        thumbnail: 'cgfc.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['action', 'casual', 'controller', 'puzzle'],
        releaseDate: '2025-04-10',
        lastUpdated: '2025-04-15',
        playCount: 7000,
        isMultiplayer: false,
    },
    {
        id: 41,
        title: 'Race Clicker Tap Tap Game',
        slug: 'race_clicker_tap_tap_game',
        originalThumbnail: 'race-clicker-tap-tap-game.jpg',
        thumbnail: 'race-clicker-tap-tap-game.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['clicker', 'casual', 'racing', 'controller'],
        releaseDate: '2025-05-05',
        lastUpdated: '2025-05-10',
        playCount: 9500,
        isMultiplayer: false,
    },
    {
        id: 42,
        title: 'Jump Guys',
        slug: 'jump_guys',
        originalThumbnail: 'jump-guys.jpg',
        thumbnail: 'jump-guys.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['action', 'adventure', 'casual', 'controller', 'stickman'],
        releaseDate: '2025-05-01',
        lastUpdated: '2025-05-05',
        playCount: 10000,
        isMultiplayer: true,
    },
    {
        id: 43,
        title: 'Goober Dash',
        slug: 'goober_dash',
        originalThumbnail: 'goober-dash.jpg',
        thumbnail: 'goober-dash.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['action', 'casual', 'racing', 'io-games'],
        releaseDate: '2025-04-25',
        lastUpdated: '2025-04-30',
        playCount: 11000,
        isMultiplayer: true,
    },
    {
        id: 44,
        title: 'Epic Empire Tower Defense',
        slug: 'epic_empire_tower_defense',
        originalThumbnail: 'epic-empire-tower-defense.jpg',
        thumbnail: 'epic-empire-tower-defense.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['tower-defense', 'strategy', 'action', 'controller'],
        releaseDate: '2025-05-15',
        lastUpdated: '2025-05-20',
        playCount: 12000,
        isMultiplayer: false,
    },
    {
        id: 45,
        title: 'Voxiom',
        slug: 'voxiom',
        originalThumbnail: 'voxiom.jpg',
        thumbnail: 'voxiom.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['io-games', 'action', 'shooting', 'minecraft', 'fps'],
        releaseDate: '2025-05-20',
        lastUpdated: '2025-05-25',
        playCount: 18000,
        isMultiplayer: true,
    },
    {
        id: 46,
        title: 'Struckd 3D Game Creator',
        slug: 'struckd_3d_game_creator',
        originalThumbnail: 'struckd-3d-game-creator.jpg',
        thumbnail: 'struckd-3d-game-creator.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['creative', 'casual', 'controller', 'puzzle'],
        releaseDate: '2025-04-05',
        lastUpdated: '2025-04-10',
        playCount: 8500,
        isMultiplayer: false,
    },
    {
        id: 47,
        title: 'Bro Royale',
        slug: 'bro_royale',
        originalThumbnail: 'bro-royale.jpg',
        thumbnail: 'bro-royale.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['2-player', 'action', 'shooting', 'io-games', 'fps'],
        releaseDate: '2025-05-25',
        lastUpdated: '2025-05-28',
        playCount: 16000,
        isMultiplayer: true,
    },
    {
        id: 48,
        title: 'Mighty Action Heroes',
        slug: 'mighty_action_heroes',
        originalThumbnail: 'mighty-action-heroes.jpg',
        thumbnail: 'mighty-action-heroes.jpg',
        url: 'https://cloud.onlinegames.io/games/2022/construct/92/kick-the-pirate/index-og.html',
        categories: ['action', 'adventure', 'shooting', 'controller', 'stickman'],
        releaseDate: '2025-05-10',
        lastUpdated: '2025-05-15',
        playCount: 14000,
        isMultiplayer: true,
    },
];
